#ifndef SENSORMEASUREMENTTYPE_H_INCLUDED
#define SENSORMEASUREMENTTYPE_H_INCLUDED

enum class SensorMeasurementType
{
    WIND_SPEED,
    AMBIENT_TEMPERATURE,
    SOLAR_RADIATION
};

#endif // SENSORMEASUREMENTTYPE_H_INCLUDED
